=== github-krishnakanth/WebServicesRepo/Xml/xsd/namespaces/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ebay.in/sales/books" xmlns:es="http://ebay.in/sales/books" elementFormDefault="qualified">
	
	<xs:element name="book" type="es:bookType"/>
	<xs:element name="name" type="xs:string"/>
	<xs:complexType name="bookType">
		<xs:sequence>
			<xs:element name="isbn" type="xs:string"/>
			<xs:element name="title" type="xs:string"/>
			<xs:element name="author" type="es:authorType"/>
			<xs:element name="publisher" type="es:publisherType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="authorType">
		<xs:sequence>
			<xs:element ref="es:name"/>
			<xs:element name="dob" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="publisherType">
		<xs:sequence>
			<xs:element ref="es:name"/>
			<xs:element name="est-date" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== github-krishnakanth/WebServicesRepo/Xml/xsd/namespaces/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ebay.in/sales/books file:///D:/work/master/webservices/20180125/Xml/xsd/namespaces/book.xsd" xmlns="http://ebay.in/sales/books">
	<isbn>isb3</isbn>
	<title>393</title>
	<author>
		<name>yaswanth</name>
		<dob>1990-01-23</dob>
	</author>
	<publisher>
		<name>wrox</name>
		<est-date>1980-01-01</est-date>
	</publisher>
</book>
