=== github-krishnakanth/WebServicesRepo/Xml/bank.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT sbi-bank (accounts, lockers)>
<!ELEMENT accounts (account+)>
<!ELEMENT account (account-holder-name, balance)>
<!ATTLIST account accountNo ID #REQUIRED>
<!ATTLIST account account-type CDATA #FIXED "savings">
<!ATTLIST account nominee NMTOKEN #REQUIRED>
<!ELEMENT account-holder-name (#PCDATA)>
<!ELEMENT balance (#PCDATA)>
<!ELEMENT lockers (locker+)>
<!ELEMENT locker (alloted-date, alloted-to, capacity, charges)>
<!ATTLIST locker lockerNo ID #REQUIRED>
<!ATTLIST locker refAccountNo IDREF #REQUIRED>
<!ELEMENT alloted-date (#PCDATA)>
<!ELEMENT alloted-to (#PCDATA)>
<!ELEMENT capacity (#PCDATA)>
<!ELEMENT charges (#PCDATA)>

=== github-krishnakanth/WebServicesRepo/Xml/bank.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sbi-bank SYSTEM "D:\work\master\webservices\20180125\Xml\bank.dtd">
<sbi-bank>
	<accounts>
		<account account-type="savings" accountNo="ac23" nominee="subbu">
			<account-holder-name>Bill</account-holder-name>
			<balance>9394</balance>
		</account>
		<account accountNo="ac24" nominee="sridhar">
			<account-holder-name>Brave</account-holder-name>
			<balance>393</balance>		
		</account>
	</accounts>
	<lockers>
		<locker lockerNo="lc1" refAccountNo="ac24">
			<alloted-date>01/01/2018</alloted-date>
			<alloted-to>Brave</alloted-to>
			<capacity>100</capacity>
			<charges>1000</charges>
		</locker>
	</lockers>
</sbi-bank>
