=== github-krishnakanth/WebServicesRepo/Xml/po.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT purchaseOrder (orderItems, shippingAddress)>
<!ELEMENT orderItems (item+)>
<!ELEMENT item (itemCode, quantity)>
<!ELEMENT itemCode (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT shippingAddress (addressLine1, addressLine2, city, state, zip, country)>
<!ATTLIST shippingAddress addressType (permanent|temporary) #REQUIRED>
<!ELEMENT addressLine1 (#PCDATA)>
<!ATTLIST addressLine1 landmark CDATA #IMPLIED>
<!ELEMENT addressLine2 (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT country (#PCDATA)>

=== github-krishnakanth/WebServicesRepo/Xml/po.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE purchaseOrder SYSTEM "D:\work\master\webservices\20180125\Xml\po.dtd">
<purchaseOrder>
	<orderItems>
		<item>
			<itemCode>ic738</itemCode>
			<quantity>abc</quantity>
		</item>
		<item>
			<itemCode>ic928</itemCode>
			<quantity>20</quantity>
		</item>
	</orderItems>
	<shippingAddress addressType="permanent">
		<addressLine1 landmark="near ameerpet x-roads">505, 5th floor</addressLine1>
		<addressLine2>Ameerpet X Roads</addressLine2>
		<city>Hyderabad</city>
		<state>TS</state>
		<zip>500072</zip>
		<country>India</country>
	</shippingAddress>
</purchaseOrder>
