=== github-krishnakanth/WebServicesRepo/Xml/policy.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT policy (insurance-details, enrollment-info)>
<!ELEMENT insurance-details (plan-name, plan-type, description, premium-amount)>
<!ELEMENT plan-name (#PCDATA)>
<!ELEMENT plan-type (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT premium-amount (#PCDATA)>
<!ELEMENT enrollment-info (term-information, policy-holder)>
<!ELEMENT term-information (policy-no, effective-dt, end-dt, premium-cycle, terms)>
<!ELEMENT policy-no (#PCDATA)>
<!ELEMENT effective-dt (#PCDATA)>
<!ELEMENT end-dt (#PCDATA)>
<!ELEMENT premium-cycle (#PCDATA)>
<!ELEMENT terms (#PCDATA)>
<!ELEMENT policy-holder (policy-holder-name,dob,gender)>
<!ELEMENT policy-holder-name (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT gender (#PCDATA)>

=== github-krishnakanth/WebServicesRepo/Xml/policy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policy SYSTEM "D:\work\master\webservices\20180125\Xml\policy.dtd">
<policy>
	<insurance-details>
		<plan-name>Jeevan Arogya</plan-name>
		<plan-type>Risk Coverage</plan-type>
		<description>Risk coverage plan for life</description>
		<premium-amount>3390.34</premium-amount>
	</insurance-details>
	<enrollment-info>
		<term-information>
			<policy-no>p394</policy-no>
			<effective-dt>01/01/2018</effective-dt>
			<end-dt>31/12/2028</end-dt>
			<premium-cycle>Halfyearly</premium-cycle>
			<terms>10</terms>
		</term-information>
		<policy-holder>
			<policy-holder-name>Mark</policy-holder-name>
			<dob>01/01/1998</dob>
			<gender>Male</gender>
		</policy-holder>
	</enrollment-info>
</policy>
