=== github-krishnakanth/WebServicesRepo/Xml/xsd/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="book" type="bookType"/>
	<xs:element name="name" type="xs:string"/>
	<xs:complexType name="bookType">
		<xs:sequence>
			<xs:element name="isb" type="xs:string"/>
			<xs:element name="title" type="xs:string"/>
			<xs:element name="category" type="categoryType"/>
			<xs:element name="author" type="authorType"/>
			<xs:element name="publisher" type="publisherType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="authorType">
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element name="dob" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="publisherType">
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element name="est-dt" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="categoryType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Fiction"/>
			<xs:enumeration value="Kids"/>
			<xs:enumeration value="Drama"/>
		</xs:restriction>	
	</xs:simpleType>
</xs:schema>

=== github-krishnakanth/WebServicesRepo/Xml/xsd/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20180125/Xml/xsd/book.xsd">
	<isb>isb3</isb>
	<title>let us c</title>
	<category>Fiction</category>
	<author>
		<name>yaswanth</name>
		<dob>1980-01-20</dob>
	</author>
	<publisher>
		<name>Bpb</name>
		<est-dt>1970-01-20</est-dt>
	</publisher>
</book>
