=== github-krishnakanth/WebServicesRepo/Xml/xsd/makemytrip.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="booking-confirmation" type="bookingConfirmationType"/>
	
	<xs:group name="reservationFieldsGroup">
		<xs:sequence>
			<xs:element name="source" type="xs:string"/>
			<xs:element name="destination" type="xs:string"/>
			<xs:element name="journey-date" type="xs:date"/>
			<xs:element name="reservation-type" type="xs:string"/>
			<xs:element name="amount" type="xs:float"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="busTicketGroup">
		<xs:sequence>
			<xs:element name="bus-ticket" type="busTicketType" />
			<xs:element name="hotel-reservation" type="hotelReservationType"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="trainTicketGroup">
		<xs:sequence>
			<xs:element name="train-ticket" type="trainTicketType" />
			<xs:element name="hotel-reservation" type="hotelReservationType"/>
		</xs:sequence>
	</xs:group>
	
	
	
	<xs:complexType name="bookingConfirmationType">
		<xs:sequence>
			<xs:element name="transaction-no" type="xs:string"/>
			<xs:element name="transaction-date" type="xs:date"/>
			<xs:element name="tickets" type="ticketsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ticketsType">
		<xs:all>
			<xs:element name="bus-ticket" type="busTicketType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="train-ticket" type="trainTicketType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="hotel-reservation" type="hotelReservationType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:all>		
	</xs:complexType>

	<xs:complexType name="busTicketType">
		<xs:sequence>
			<xs:group ref="reservationFieldsGroup"/>
			<xs:element name="bus-no" type="xs:string"/>
			<xs:element name="seat-no" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="trainTicketType">
		<xs:sequence>
			<xs:group ref="reservationFieldsGroup"/>
			<xs:element name="pnr-no" type="xs:string"/>
			<xs:element name="coach" type="xs:string"/>
			<xs:element name="berth" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="hotelReservationType">
		<xs:sequence>
			<xs:group ref="reservationFieldsGroup"/>
			<xs:element name="checkin-date" type="xs:date"/>
			<xs:element name="purpose" type="xs:string"/>
			<xs:element name="days-of-stay" type="xs:int"/>
			<xs:element name="room-no" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== github-krishnakanth/WebServicesRepo/Xml/xsd/makemytrip.xml
<?xml version="1.0" encoding="UTF-8"?>
<booking-confirmation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20180125/Xml/xsd/makemytrip.xsd">
	<transaction-no>t93</transaction-no>
	<transaction-date>2018-03-31</transaction-date>
	<tickets>
		<bus-ticket>
			<source>hyderbad</source>
			<destination>banglore</destination>
			<journey-date>2018-04-30</journey-date>
			<reservation-type>Volvo Ac</reservation-type>
			<amount>2000</amount>
			<bus-no>b93</bus-no>
			<seat-no>22</seat-no>
		</bus-ticket>		
		<hotel-reservation>
			<source>banglore</source>
			<destination>chennai</destination>
			<journey-date>2018-04-30</journey-date>
			<reservation-type>luxury</reservation-type>
			<amount>3029</amount>
			<checkin-date>2018-05-23</checkin-date>
			<purpose>Personal</purpose>
			<days-of-stay>3</days-of-stay>
			<room-no>3</room-no>
		</hotel-reservation>
		
		<train-ticket>
			<source>banglore</source>
			<destination>chennai</destination>
			<journey-date>2018-05-30</journey-date>
			<reservation-type>sleeper</reservation-type>
			<amount>2000</amount>
			<pnr-no>39404</pnr-no>
			<coach>s1</coach>
			<berth>20</berth>
		</train-ticket>
		
	</tickets>
</booking-confirmation>
