=== github-krishnakanth/WebServicesRepo/Xml/xsd/po.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="purchaseOrder" type="purchaseOrderType"/>
	<xs:complexType name="purchaseOrderType">
		<xs:sequence>
			<xs:element name="orderItems" type="orderItemsType"/>
			<xs:choice>
				<xs:element name="shippingAddress" type="shippingAddressType"/>
				<xs:element name="usShippingAddress" type="usShippingAddressType"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="orderItemsType">
		<xs:sequence>
			<xs:element name="item" type="itemType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="itemType">
		<xs:sequence>
			<xs:element name="itemCode" type="xs:string"/>
			<xs:element name="quantity" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="shippingAddressType">
		<xs:sequence>
			<xs:element name="addressLine1" type="addressLine1Type"/>
			<xs:element name="addressLine2" type="xs:string"/>
			<xs:element name="city" type="cityType"/>
			<xs:element name="state" type="xs:string"/>
			<xs:element name="zip" type="zipType"/>
			<xs:element name="country" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="addressType" type="addressEnumType" use="required"/>
	</xs:complexType>
	<xs:complexType name="usShippingAddressType">
		<xs:complexContent>
			<xs:extension base="shippingAddressType">
				<xs:sequence>
					<xs:element name="county" type="xs:int"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="zipType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="99999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="addressEnumType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="permanent"/>
			<xs:enumeration value="temporary"/>
		</xs:restriction>	
	</xs:simpleType>
	
	<xs:complexType name="addressLine1Type">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="landmark" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="cityType">
		<xs:simpleContent>
			<xs:extension base="cityEnumType">
				<xs:attribute name="zone" type="zoneEnumType" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="zoneEnumType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="east"/>
			<xs:enumeration value="west"/>
			<xs:enumeration value="south"/>
			<xs:enumeration value="north"/>
		</xs:restriction>	
	</xs:simpleType>
	<xs:simpleType name="cityEnumType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Hyderabad"/>
			<xs:enumeration value="Banglore"/>
			<xs:enumeration value="Chennai"/>
		</xs:restriction>	
	</xs:simpleType>
</xs:schema>

=== github-krishnakanth/WebServicesRepo/Xml/xsd/po.xml
<?xml version="1.0" encoding="UTF-8"?>
<purchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20180125/Xml/xsd/po.xsd">
	<orderItems>
		<item>
			<itemCode>ic738</itemCode>
			<quantity>21</quantity>
		</item>
		<item>
			<itemCode>ic928</itemCode>
			<quantity>20</quantity>
		</item>
	</orderItems>
	
	<shippingAddress addressType="permanent">		
		<addressLine1 landmark="Near Ameerpet X Roads">505, 5th floor</addressLine1>		
		<addressLine2>Ameerpet X Roads</addressLine2>
		<city zone="east">Banglore</city>
		<state>TS</state>
		<zip>1111</zip>
		<country>India</country>		
	</shippingAddress>
</purchaseOrder>

=== github-krishnakanth/WebServicesRepo/pojaxb/resource/po.xml
<?xml version="1.0" encoding="UTF-8"?>
<purchaseOrder
	xsi:schemaLocation="http://ebay.in/sales/types file:///C:/work/20180122/pojaxb/resource/po.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://ebay.in/sales/types">
	<orderItems>
		<item>
			<itemCode>ic738</itemCode>
			<quantity>21</quantity>
		</item>
		<item>
			<itemCode>ic928</itemCode>
			<quantity>20</quantity>
		</item>
	</orderItems>

	<shippingAddress addressType="permanent">
		<addressLine1 landmark="Near Ameerpet X Roads">505, 5th floor</addressLine1>
		<addressLine2>Ameerpet X Roads</addressLine2>
		<city zone="east">Banglore</city>
		<state>TS</state>
		<zip>1111</zip>
		<country>India</country>
	</shippingAddress>
</purchaseOrder>

=== github-krishnakanth/WebServicesRepo/Xml/xsd/namespaces/po.xml
<?xml version="1.0" encoding="UTF-8"?>
<ab:purchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://amazon.in/book/store/types  file:///D:/work/master/webservices/20180125/Xml/xsd/namespaces/po.xsd" xmlns:ab="http://amazon.in/book/store/types">
	<ab:orderItems>
		<ab:item>
			<ab:itemCode>ic3</ab:itemCode>
			<ab:quantity>24</ab:quantity>
		</ab:item>
	</ab:orderItems>
	<ab:shippingAddress>
		<ab:addressLine1>afd</ab:addressLine1>
		<ab:addressLine2>af</ab:addressLine2>
		<ab:city>safd</ab:city>
		<ab:state>asfd</ab:state>
		<ab:zip>25</ab:zip>
		<ab:country>adff</ab:country>
	</ab:shippingAddress>
</ab:purchaseOrder>
