=== github-krishnakanth/WebServicesRepo/Xml/xsd/trip.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="trip">
		<xs:complexType>
			<xs:sequence>	
				<xs:element name="booking-no" type="xs:string"/>
				<xs:element name="trip-date" type="xs:date"/>
				<xs:element name="duration" type="xs:string"/>
				<xs:element name="package-name" type="xs:string"/>
				<xs:element name="amount" type="xs:float"/>
				<xs:element name="itenary">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="visit">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="day" type="xs:int"/>
										<xs:element name="place" type="xs:string"/>
										<xs:element name="description" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="includes" type="xs:string"/>
				<xs:element name="terms-and-conditions" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== github-krishnakanth/WebServicesRepo/Xml/xsd/trip.xml
<?xml version="1.0" encoding="UTF-8"?>
<trip xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20180125/Xml/xsd/trip.xsd">
	<booking-no>b349</booking-no>
	<trip-date>2018-03-25</trip-date>
	<duration>4 days and 5 nights</duration>
	<package-name>Himachal Pradesh Package</package-name>
	<amount>9384</amount>
	<itenary>
		<visit>
			<day>1</day>
			<place>Shimla</place>
			<description>Hills</description>
		</visit>
	</itenary>
	<includes>flight and hotel stay</includes>
	<terms-and-conditions>No cancellation</terms-and-conditions>
</trip>
